site_name: ICEpy4D
repo_url: https://github.com/franioli/icepy4d
site_author: Francesco Ioli

theme:
  name: material
  palette:
    primary: indigo
  font:
    text: Open Sans
  features:
    - navigation.path
    - navigation.footer

plugins:
  - search
  - autorefs
  # - gen-files:
  #     scripts:
  #     - docs/gen_ref_pages.py  # 
  - mkdocstrings:
      handlers:
        python:
          paths: [src] # search packages in the src folder
          options:
            show_source: false
            heading_level: 2

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting started: getting_started.md
  - Modules:
      - Core:
          - Epoch: core/epoch.md
          - Camera: core/camera.md
          - Images: core/images.md
          - Features: core/features.md
          - Points: core/points.md
          - Point Cloud: core/point_cloud.md
          - Targets: core/targets.md
      - Matching:
          - Matching: matching/matching.md
          - Tracking: matching/tracking.md
          - Templatematch: matching/templatematch.md
      - Sfm:
          - Two-view Geometry: sfm/two_view_geometry.md
          - Absolute orientation: sfm/absolute_orientation.md
          - Triangulation: sfm/triangulation.md
          - Incremental reconstruction: sfm/reconstruction.md
      - Visualization: visualization.md
