site_name: ICEpy4D

theme:
  name: material
  palette:
    primary: indigo
  font:
    text: Open Sans
  features:
    - navigation.path
    - navigation.footer

repo_url: https://github.com/franioli/icepy4d

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - Classes:
      - Camera: camera.md
