name: Deploy docs

on: [push, pull_request]
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      # - name: Install Python libs
      #   run: |
      #     pip install --no-deps -r requirements-dev.txt
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Deploy to gh-pages
        run: mkdocs gh-deploy --force
